#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Zend\ServiceManager\ServiceManager;

set_time_limit(0);

require 'vendor/autoload.php';

// create service manager
$container = new ServiceManager(
    require 'src/App/services.php'
);

// create symfony console
$console = new Application();
$console->setName('Tornado Http Skeleton Console');

// add custom register commands
foreach (glob('src/App/Console/Register/*.php') as $commandName) {
    $fullCommandName = 'App\\Console\\Register\\'.str_replace('/', '\\', ltrim(rtrim($commandName, '.php'), 'src/App/Console/Register'));
    new $fullCommandName($console, $container);
}

// add custom application commands
foreach (glob('src/App/Console/Command/*.php') as $commandName) {
    $fullCommandName = 'App\\Console\\Command\\'.str_replace('/', '\\', ltrim(rtrim($commandName, '.php'), 'src/App/Console/Command'));
    $command = new $fullCommandName($container);
    $console->add($command);
}

// run console
$console->run();
